self.addEventListener('install',e=>{
  e.waitUntil(caches.open('static-v1').then(c=>c.addAll([
    '/',
    '/index.html',
    '/styles/tokens.css','/styles/base.css','/styles/layout.css','/styles/components.css','/styles/theme.css','/styles/map.css',
    '/scripts/init.js','/scripts/router.js','/scripts/data.js','/scripts/map.js','/scripts/timeline.js','/scripts/cities.js'
  ])));
});
self.addEventListener('fetch',e=>{
  e.respondWith(caches.match(e.request).then(r=>r||fetch(e.request)));
});
